version: "3.7"
services:
  django_database:
    image: postgres:15.3
    volumes:
      - django_database_pet:/var/lib/postgresql/data
    container_name: app_django_database
    command: -p 1222
    ports:
      - "5432:1222"
    env_file:
      - .env
    restart: always
    networks:
      - app_django_network

  django_gunicorn:
    build:
      context: .
    container_name: app_django
    volumes:
      - static:/static
    restart: always
    env_file:
      - .env
    command: [ "/app/docker_start/start.sh" ]
    ports:
      - "8015:8015"
    depends_on:
      - django_database
    networks:
      - app_django_network

  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app_django
    networks:
      - app_django_network


networks:
  app_django_network:
    name: app_django_network
    driver: bridge

volumes:
  static:
  django_database_pet:
    driver: local